title: CSV Classification Challenge
short_description: CSV classification challenge with accuracy, precision, recall, and F1 score metrics.
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: This leaderboard ranks submissions based on their accuracy, precision, recall, and F1 score.
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2024-07-20 00:00:00
end_date: 2025-01-20 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["Accuracy", "Precision", "Recall", "F1 Score"],
        "default_order_by": "F1 Score",
        "metadata": {
          "Accuracy": {
            "sort_ascending": False,
            "description": "Accuracy of the model."
          },
          "Precision": {
            "sort_ascending": False,
            "description": "Precision of the model."
          },
          "Recall": {
            "sort_ascending": False,
            "description": "Recall of the model."
          },
          "F1 Score": {
            "sort_ascending": False,
            "description": "F1 Score of the model."
          }
        }
      }

challenge_phases:
  - id: 1
    name: Single Phase
    description: templates/challenge_phase_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2024-07-20 00:00:00
    end_date: 2025-01-20 23:59:59
    test_annotation_file: annotations/ground_truth.csv  # Path to your ground truth labels
    codename: single_phase
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 50
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: TextAttribute
        description: Sample
        type: text
        required: False
      - name: SingleOptionAttribute
        description: Sample
        type: radio
        options: ["A", "B", "C"]
      - name: MultipleChoiceAttribute
        description: Sample
        type: checkbox
        options: ["alpha", "beta", "gamma"]
      - name: TrueFalseField
        description: Sample
        type: boolean
        required: True
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".csv"

dataset_splits:
  - id: 1
    name: Train Split
    codename: train_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
